stages:
  - validate

validate_branch:
  stage: validate
  script:
    - echo "Validating branch name..."
    - ./scripts/.git-scripts/validate-branch.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "production" || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "prelaunch"'
      when: never
    - when: always

validate_commit:
  stage: validate
  script:
    - echo "Validating commit messages..."
    - commits=$(git log --oneline --no-merges)
    - while IFS= read -r commit; do
        commit_msg=$(echo "$commit" | cut -d' ' -f2-);
        echo $commit_msg;
        bash ./scripts/.git-scripts/validate-commit.sh "$commit_msg";
      done <<< "$commits"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "production" || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "prelaunch"'
      when: never
    - when: always
