name: Branch and Commit Validation

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate branch name
      run: |
        bash ./scripts/.github/validate-branch.sh

    - name: Validate commit messages
      run: |
        commits=$(git log --oneline --no-merges)
        for commit in $commits; do
          commit_msg=$(echo "$commit" | cut -d' ' -f2-)
          bash ./scripts/.github/validate-commit.sh "$commit_msg"
        done
